db:
  host: localhost
  port: 5432
  POSTGRES_ROOT_PASSWORD: postgres
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: capsmhoo
rabbitmq:
  url: amqp://guest:guest@localhost:5672/
  noti_queue_name: capsmhooo-noti
user-service:
  host: 127.0.0.1
  port: 8080
team-service:
  port: 8081
  grpc-host: 127.0.0.1
  grpc-port: 50051
noti-service:
  grpc-host: 127.0.0.1
  grpc-port: 50054
api-gateway:
  port: 8082
team-join-request-service:
  port: 8085
  grpc-host: 127.0.0.1
  grpc-port: 50055

