db:
  host: localhost
  port: 5432
  POSTGRES_ROOT_PASSWORD: postgres
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: capsmhoo
user-service:
  port: 8080
team-service:
  port: 8081
  grpc-host: 127.0.0.1
  grpc-port: 50051
api-gateway:
  port: 8082

