name: Build and Test Server

on:
  push:
    branches: [ "master", "dev" ]
    paths:
      - "server/**"
  pull_request:
    branches: [ "master", "dev" ]
    paths:
      - "server/**"
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Change to server directory
      run: cd server

    - name: Build User Service
      run: go build -v cmd/user/main.go

    - name: Build Team Service
      run: go build -v cmd/team/main.go

    - name: Build Project Service
      run: go build -v cmd/proj/main.go

    - name: Build API Gateway
      run: go build -v cmd/gateway/main.go
