name: Build and Test Server

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
  push:
    branches: [ "master", "dev" ]
    paths:
      - "server/**"
      - ".github/workflows/build-test-server.yml"
  pull_request:
    branches: [ "master", "dev" ]
    paths:
      - "server/**"
      - ".github/workflows/build-test-server.yml"
jobs:

  build_user:
    name: Build User Service
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      working-directory: ./server
      run: go build -v cmd/user/main.go

 build_team:
    name: Build Team Service
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      working-directory: ./server
      run: go build -v cmd/team/main.go

 build_project:
    name: Build Project Service
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      working-directory: ./server
      run: go build -v cmd/proj/main.go
  
  build_noti:
    name: Build Noti Service
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      working-directory: ./server
      run: go build -v cmd/noti/main.go

  build_gateway:
    name: Build Api Gateway
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build API Gateway
      working-directory: ./server
      run: go build -v cmd/gateway/main.go
